### ISSUE TITLE
Does Hololens2 have plan to support offline TTS suport?

### ISSUE THREAD

**Issue by Hawkpool** [microsoft/MixedReality-GraphicsTools-Unreal#27]
Does Hololens2 have plan to support offline TTS suport?

**Comment by Cameron-Micka** [comment]
Hi @Hawkpool, offline text to speech isn't part of Graphics Tools. But because HoloLens 2 is a Windows device it does have TTS support. The [OpenXR ](https://github.com/microsoft/Microsoft-OpenXR-Unreal)plugin provides options to bind speech commands to Unreal input actions: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-voice-input

There might also be a way to synthesize speech with [this ](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.SpeechSynthesis.SpeechSynthesizer?redirectedfrom=MSDN&view=winrt-22621) UWP class. @fieldsJacksonG might have more info to share.
